version: "3.8"

services:
  # Proxy reverso
  haproxy:
    hostname: caminhointernoservicos
    image: haproxytech/haproxy-debian:2.5
    depends_on:
      - db
      - web-api
      - api-gateway
      - web-app
    volumes:
      - ../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        #- /path/to/certificate/.pem:/path/to/certificate/.pem:ro
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - "80:8000"
      - "443:443"
      - "8404:8404"
    networks:
      - pgd
      - pgd-interno
    
  web-api:
    # Futuro oficial do Governo Federal
    #image: ghcr.io/spbgovbr/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem do SrMouraSilva enquanto o ME não corrige o repositório...
    image: ghcr.io/srmourasilva/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem caso você queira testar na sua máquina
    #image: susep
    working_dir: /app/api/
    command: dotnet Susep.SISRH.WebApi.dll
    volumes:
      - ./api/Settings:/app/api/Settings:ro
      #- ../install/Arquivos de configuração/1. Susep.SISRH.WebApi/Settings:/app/api/Settings:ro
      - ../log/api:/app/api/Logs:rw
    environment: 
      - ASPNETCORE_ENVIRONMENT=Homolog

      # Configurações de banco de dados
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=programa_gestao;User Id=sa;Password=P1ssw@rd;

      # Configurações de e-mail - Exemplo: Ministério da Economia
      - emailOptions__EmailRemetente=no-reply@me.gov.br
      - emailOptions__NomeRemetente=Programa de Gestão - ME
      - emailOptions__SmtpServer=smtp.me.gov.br
      - emailOptions__Port=25

      # LDAP
      # -> URL do Servidor LDAP
      - ldapOptions__Configurations__0__Url=
      # -> Porta do Servidor LDAP
      - ldapOptions__Configurations__0__Port=389
      # -> DN do usuário de serviço que será utilizado para autenticar no LDAP"
      - ldapOptions__Configurations__0__BindDN=CN=Fulano de tal,CN=Users,DC=orgao
      # -> Senha do usuário de serviço que será utilizado para autenticar no LDAP
      - ldapOptions__Configurations__0__BindPassword=
      # -> DC que será utilizado para chegar à base de usuários no LDAP
      - ldapOptions__Configurations__0__SearchBaseDC=CN=Users,DC=orgao
      # -> Consulta a ser aplicada no LDAP para encontrar os usuários
      - ldapOptions__Configurations__0__SearchFilter=(&(objectClass=user)(objectClass=person)(sAMAccountName={0}))
      # -> Campo do LDAP em que será encontrado o CPF do usuário
      - ldapOptions__Configurations__0__CpfAttributeFilter=
      # -> Campo do LDAP em que será encontrado o e-mail do usuário
      - ldapOptions__Configurations__0__EmailAttributeFilter=

    # Habilitar somente para debug
    # ports:
    #   - 8082:80
    networks:
      - pgd-interno

  api-gateway:
    # Futuro oficial do Governo Federal
    #image: ghcr.io/spbgovbr/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem do SrMouraSilva enquanto o ME não corrige o repositório...
    image: ghcr.io/srmourasilva/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem caso você queira testar na sua máquina
    #image: susep
    command: dotnet Susep.SISRH.ApiGateway.dll
    working_dir: /app/gateway/
    volumes:
      - ./gateway/Settings:/app/gateway/Settings:ro
      - ../log/gateway:/app/gateway/Logs:rw
    environment: 
      - ASPNETCORE_ENVIRONMENT=Homolog
    networks:
      - pgd
      - pgd-interno

  web-app:
    # Futuro oficial do Governo Federal
    #image: ghcr.io/spbgovbr/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem do SrMouraSilva enquanto o ME não corrige o repositório...
    image: ghcr.io/srmourasilva/sistema_programa_de_gestao_susep/sgd:latest
    # Imagem caso você queira testar na sua máquina
    #image: susep
    command: dotnet Susep.SISRH.WebApp.dll
    working_dir: /app/app/
    volumes:
      - ./app/env.js:/app/app/ClientApp/dist/env.js:ro
    networks:
      - pgd

  ## FIXME - Utilização do Nginx no lugar do aspnet
  # web-app-nginx:
  #   image: nginx:1.19-alpine
  #   volumes:
  #     - ./install/3. Susep.SISRH.WebApp/ClientApp/dist:/usr/share/nginx/html:rw
  #     - ./install/Arquivos de configuração/3. Susep.SISRH.WebApp/ClientApp/dist/env.js:/usr/share/nginx/html/env.js:ro
  #   ports:
  #     - 8080:80

networks:
  pgd:
  pgd-interno:
